// Font bundler for the QuestLog offline app.
// Adapted from jvds-game-maker-app/fetch-fonts.mjs
import { writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, 'fonts');

const CSS_URLS = [
  'https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:wght@400;700&family=Nunito:wght@400;700;900&family=JetBrains+Mono:wght@400;500;700&display=swap',
  'https://fonts.googleapis.com/css2?family=Cinzel:wght@700&family=Orbitron:wght@700;900&display=swap',
];

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const slug = (s) => s.replace(/['"]/g, '').trim().replace(/\s+/g, '');

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return res.text();
}

async function fetchBin(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

function splitBlocks(css) {
  const out = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m;
  while ((m = re.exec(css))) out.push({ subset: m[1], block: m[2] });
  return out;
}

const field = (block, name) => {
  const m = block.match(new RegExp(name + '\\s*:\\s*([^;]+);'));
  return m ? m[1].trim() : '';
};

async function main() {
  if (existsSync(outDir)) rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const cssOut = [
    '/* Self-hosted Google Fonts for offline use. Generated by fetch-fonts.mjs.',
    '   Families: Bebas Neue, Inter, Nunito, JetBrains Mono, Cinzel, Orbitron.',
    '   Do not hand-edit; re-run the script instead. */',
    '',
  ];
  const seen = new Set();
  let files = 0, bytes = 0;

  for (const url of CSS_URLS) {
    const css = await fetchText(url);
    for (const { subset, block } of splitBlocks(css)) {
      if (!KEEP_SUBSETS.has(subset)) continue;
      const family = field(block, 'font-family');
      const weight = field(block, 'font-weight') || '400';
      const style = field(block, 'font-style') || 'normal';
      const srcM = block.match(/url\(([^)]+)\)\s*format\(['"]woff2['"]\)/);
      if (!srcM) continue;
      const woff2Url = srcM[1].replace(/['"]/g, '');

      const name = `${slug(family)}-${weight}-${style === 'italic' ? 'i' : 'n'}-${subset}.woff2`;
      if (!seen.has(name)) {
        const buf = await fetchBin(woff2Url);
        writeFileSync(join(outDir, name), buf);
        seen.add(name);
        files++; bytes += buf.length;
        console.log(`  ${name}  (${(buf.length / 1024).toFixed(1)} KB)`);
      }
      const local = block.replace(/url\([^)]+\)\s*format\(['"]woff2['"]\)/, `url(./${name}) format('woff2')`);
      cssOut.push(`/* ${slug(family)} ${weight} ${style} ${subset} */`);
      cssOut.push(local.trim());
      cssOut.push('');
    }
  }

  writeFileSync(join(outDir, 'fonts.css'), cssOut.join('\n'), 'utf8');
  console.log(`\nfonts: ${files} woff2 file(s), ${(bytes / 1024).toFixed(1)} KB total`);
  console.log(`written to ${outDir}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
